// front-angular/src/app/views/home/home.component.ts
import { Component, Input, OnInit } from "@angular/core";

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.css"],
})
export class HomeComponent implements OnInit {
  @Input() msg: string = "";
  legend = "Im in Angular";

  constructor() {}

  ngOnInit(): void {}

  resetLegend(): void {
    console.log("Event of click in angular");
    this.legend = "Im in Angular";
  }
}

<h1>{{ msg }}</h1>
<h2>{{ legend }}</h2>

<input type="text" [value]="legend">

<button (click)="resetLegend()">Reset Legend</button><br><br>

<input type="text" [(ngModel)]="legend">

// front-react/src/views/home/Home.jsx
import React, { useState } from "react";

function Home(props) {
    let [legend, setLegend] = useState('Im in React')

    function resetLegend() {
        console.log('Event of click in React');
        setLegend('Im in React')
    }

    return (
        <section>
            <h1>{ props.msg }</h1>
            <h2>{ legend }</h2>
            <input type="text" value={legend} readOnly />
            <button onClick={resetLegend}>Reset legend</button><br /><br />

            <input type="text" value={legend} onChange={e => setLegend(e.target.value)} />
        </section>
    )
}

export default Home;
